// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-uO_7X5iufnITqkZY_No-4CpAfuXq7yE',
    appId: '1:162389671929:web:44348e1c5d9c965d2e0728',
    messagingSenderId: '162389671929',
    projectId: 'back-to-you-584e7',
    authDomain: 'back-to-you-584e7.firebaseapp.com',
    storageBucket: 'back-to-you-584e7.firebasestorage.app',
    measurementId: 'G-G3B9YC0GQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD83imd0hTwYnpqAQJGQAY6AbPyLy8n9kk',
    appId: '1:162389671929:android:a84b2ea05a9b36b72e0728',
    messagingSenderId: '162389671929',
    projectId: 'back-to-you-584e7',
    storageBucket: 'back-to-you-584e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDro6vI7PHfV26ko4C0qG5Cvp_dnGPg59Y',
    appId: '1:162389671929:ios:cc4fc84b8d6f94572e0728',
    messagingSenderId: '162389671929',
    projectId: 'back-to-you-584e7',
    storageBucket: 'back-to-you-584e7.firebasestorage.app',
    iosBundleId: 'com.example.backToYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDro6vI7PHfV26ko4C0qG5Cvp_dnGPg59Y',
    appId: '1:162389671929:ios:cc4fc84b8d6f94572e0728',
    messagingSenderId: '162389671929',
    projectId: 'back-to-you-584e7',
    storageBucket: 'back-to-you-584e7.firebasestorage.app',
    iosBundleId: 'com.example.backToYou',
  );
}
